goodbyes_data = [
    "Goodbye",
    "Farewell",
    "See you later",
    "Take care",
    "Goodbye for now",
    "Bye-bye",
    "Have a great day",
    "Have a good one",
    "See you soon",
    "Until next time",
    "Catch you later",
    "Goodbye, have a nice day",
    "Goodbye, see you next time",
    "Goodbye, see you when we can",
    "Till we meet again",
    "Au revoir",
    "See you when you need me",
]